package com.megayasa.Frontend.View.Produksi;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.google.inject.Guice;
import com.megayasa.Backend.Controllers.InventoryController;
import com.megayasa.Backend.Utils.Injection;
import com.megayasa.Backend.ViewModels.Requests.InventoryRequestVm;
import com.megayasa.Backend.ViewModels.Responses.InventoryResponseVm;
import com.megayasa.Frontend.Asset.menu.FormManager;

import java.awt.Font;
import javax.swing.*;

/**
 *
 * @author Ridho Multazam
 */
public class tambahBarang extends javax.swing.JFrame {

    private InventoryController inventoryController;
    private String inventoryCode;

    /**
     * Creates new form Test
     */
    public tambahBarang(String code) {
        inventoryCode = code;
        initComponents();
        initializeData();
    }

    public tambahBarang() {
        initComponents();
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        KodeBarang = new javax.swing.JLabel();
        txkodeBarang = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JLabel();
        txnamaBarang = new javax.swing.JTextField();
        Stock = new javax.swing.JLabel();
        txstockBarang = new javax.swing.JTextField();
        Tipe = new javax.swing.JLabel();
        txtipeBarang = new javax.swing.JTextField();
        btSimpan = new javax.swing.JButton();

        dateChooser.setForeground(new java.awt.Color(15, 42, 61));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 67, 69));
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "font:bold +1",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "wrap,al lead",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Tambah Barang");
        crazyPanel1.add(Title);

        subTitle.setText("Data Barang Baru");
        crazyPanel1.add(subTitle);

        KodeBarang.setText("Kode Barang");
        crazyPanel1.add(KodeBarang);
        crazyPanel1.add(txkodeBarang);

        NamaBarang.setText("Nama Barang");
        crazyPanel1.add(NamaBarang);
        crazyPanel1.add(txnamaBarang);

        Stock.setText("Stock");
        crazyPanel1.add(Stock);
        crazyPanel1.add(txstockBarang);

        Tipe.setText("Tipe Barang");
        crazyPanel1.add(Tipe);
        crazyPanel1.add(txtipeBarang);

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSimpan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        Integer stok = txstockBarang.getText().equals("") ? 0 : Integer.parseInt(txstockBarang.getText());
       InventoryRequestVm saveInventory =  new InventoryRequestVm(txkodeBarang.getText(), txnamaBarang.getText(),
                stok, txtipeBarang.getText());
        if (inventoryCode != null) {
            inventoryController.updateInventoryByCode(inventoryCode, saveInventory);
        } else {
            inventoryController.createInventory(saveInventory);
        }
        this.setVisible(false);
        FormManager.showForm(new Penyimpanan());
    }//GEN-LAST:event_btSimpanActionPerformed


    public static void main(String args[]) {
     FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("addThemes");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tambahBarang().setVisible(true);
            }
        });
    }

    private void initializeData() {
        inventoryController = Guice.createInjector(new Injection()).getInstance(InventoryController.class);

        if (inventoryCode != null) {
            Title.setText("Perbarui Barang");
            txkodeBarang.setEditable(false);
            subTitle.setText("Perbarui Data Barang");
            InventoryResponseVm inventorySearch = inventoryController.findInventoryByIdOrCode(inventoryCode);
            if (inventorySearch != null) {
                txkodeBarang.setText(inventorySearch.getCode());
                txnamaBarang.setText(inventorySearch.getName());
                txstockBarang.setText(inventorySearch.getStock().toString());
                txtipeBarang.setText(inventorySearch.getType());
            }
        }


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KodeBarang;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel Tipe;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btSimpan;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JLabel subTitle;
    private javax.swing.JTextField txkodeBarang;
    private javax.swing.JTextField txnamaBarang;
    private javax.swing.JTextField txstockBarang;
    private javax.swing.JTextField txtipeBarang;
    // End of variables declaration//GEN-END:variables
}
