package com.megayasa.Frontend.View.Pengaturan;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.google.inject.Guice;
import com.megayasa.Backend.Controllers.AccountController;
import com.megayasa.Backend.Controllers.EmployeeController;
import com.megayasa.Backend.Controllers.RoleController;
import com.megayasa.Backend.Models.Account;
import com.megayasa.Backend.Models.Employee;
import com.megayasa.Backend.Models.Role;
import com.megayasa.Backend.Utils.Injection;
import com.megayasa.Backend.ViewModels.Requests.AccountRequestVm;
import com.megayasa.Backend.ViewModels.Responses.EmployeeResponseVm;
import com.megayasa.Frontend.Asset.menu.FormManager;
import com.megayasa.Frontend.Helpers.ComboBoxListCellRender;

import java.awt.Font;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Ridho Multazam
 */
public class tambahAkun extends javax.swing.JFrame {


    /**
     * Creates new form Test
     */
    private AccountController accountController;
    private EmployeeController employeeController;
    private RoleController roleController;
    private String accountId;
    private List<EmployeeResponseVm> allEmployees;
    private List<Role> allRoles;
    public tambahAkun(String accountId) {
        this.accountId = accountId;
        initComponents();
        initializeData();
    }

    public tambahAkun() {
        initComponents();
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        txFirst = new javax.swing.JTextField();
        txLast = new javax.swing.JTextField();
        idKaryawan = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        Telepon = new javax.swing.JLabel();
        txNumber = new javax.swing.JTextField();
        Karyawan = new javax.swing.JLabel();
        jcKaryawan = new javax.swing.JComboBox<>();
        Status = new javax.swing.JLabel();
        jAktif = new javax.swing.JRadioButton();
        jtidakAktif = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        subTitle2 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        Karyawan1 = new javax.swing.JLabel();
        jcRole = new javax.swing.JComboBox<>();
        btSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 67, 69));
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "font:bold +1",
                "",
                "showClearButton:true;JTextField.placeholderText=Nama Depan",
                "showClearButton:true;JTextField.placeholderText=Nama Belakang",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                "",
                "",
                "",
                "",
                "",
                "font:bold +1",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true"
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "wrap,al lead",
                "",
                "split 2",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "split 2",
                "",
                "span 2,grow 1",
                "wrap,al lead",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Tambah Akun");
        crazyPanel1.add(Title);

        subTitle.setText("Personal");
        crazyPanel1.add(subTitle);

        Nama.setText("Nama Lengkap");
        crazyPanel1.add(Nama);
        crazyPanel1.add(txFirst);
        crazyPanel1.add(txLast);

        idKaryawan.setText("Email");
        crazyPanel1.add(idKaryawan);
        crazyPanel1.add(txEmail);

        Telepon.setText("No Telepon");
        crazyPanel1.add(Telepon);
        crazyPanel1.add(txNumber);

        Karyawan.setText("Karyawan");
        crazyPanel1.add(Karyawan);
        crazyPanel1.add(jcKaryawan);

        Status.setText("Status");
        crazyPanel1.add(Status);

        status.add(jAktif);
        jAktif.setText("Aktif");
        crazyPanel1.add(jAktif);

        status.add(jtidakAktif);
        jtidakAktif.setText("Tidak Aktif");
        crazyPanel1.add(jtidakAktif);
        crazyPanel1.add(jSeparator1);

        subTitle2.setText("Login");
        crazyPanel1.add(subTitle2);

        Username.setText("Username");
        crazyPanel1.add(Username);
        crazyPanel1.add(txUsername);

        Password.setText("Password");
        crazyPanel1.add(Password);

        jPassword.setText("jPasswordField1");
        crazyPanel1.add(jPassword);

        Karyawan1.setText("Role");
        crazyPanel1.add(Karyawan1);
        crazyPanel1.add(jcRole);

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSimpan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        String fullName = txFirst.getText() + " " + txLast.getText();
        String email = txEmail.getText();
        String userName = txUsername.getText();
        String password = jPassword.getText();
        String phoneNumber = txNumber.getText();
        Boolean isActive = jAktif.isSelected();
        Role role = (Role) jcRole.getSelectedItem();
        String roleId = role.getId() != null ? role.getId() : null;
        EmployeeResponseVm employee = (EmployeeResponseVm) jcKaryawan.getSelectedItem();
        String employeeId = employee.getId() != null ? employee.getId() : null;
        AccountRequestVm accountRequestVm = new AccountRequestVm(fullName, userName, email, password, phoneNumber, isActive, roleId, employeeId);

        if (accountId != null) {
            accountController.updateAccount(accountId, accountRequestVm);
        } else {
            accountController.createAccount(accountRequestVm);
        }

        this.setVisible(false);
        FormManager.showForm(new Akun());

    }//GEN-LAST:event_btSimpanActionPerformed

    private void initializeData() {
        accountController = Guice.createInjector(new Injection()).getInstance(AccountController.class);
        employeeController = Guice.createInjector(new Injection()).getInstance(EmployeeController.class);
        roleController = Guice.createInjector(new Injection()).getInstance(RoleController.class);
        loadComboBoxEmployeeValues();
        loadComboBoxRoleValues();
        fillValues();
    }

    private void fillValues() {
        if (accountId != null) {
            Title.setText("Perbarui Akun");
            Account accountById = accountController.findAccountById(accountId);
            String[] partsFullName = accountById.getFullName().split(" ", 2);
            txFirst.setText(partsFullName[0]);
            txLast.setText(partsFullName[1]);
            txEmail.setText(accountById.getEmail());
            txNumber.setText(accountById.getPhoneNumber());

            if (accountById.getEmployeeId() != null) {
                EmployeeResponseVm employeeResponseVm = allEmployees.stream().filter(e -> e.getId().equals(accountById.getEmployeeId())).findFirst().orElse(null);
                jcKaryawan.setSelectedItem(employeeResponseVm);
            }

            if (accountById.getIsActive()) {
                jAktif.setSelected(true);
            } else {
                jtidakAktif.setSelected(true);
            }

            txUsername.setText(accountById.getUsername());
            Role role = allRoles.stream().filter(r -> r.getId().equals(accountById.getRoleId())).findFirst().orElse(null);
            jcRole.setSelectedItem(role);
            jPassword.setText("");
        }
    }

    private void loadComboBoxEmployeeValues() {
        DefaultComboBoxModel<EmployeeResponseVm> defaultComboBoxModel = new DefaultComboBoxModel<>();
        allEmployees = employeeController.findAllEmployees();
        defaultComboBoxModel.addElement(new EmployeeResponseVm(null, " ", "Pilih Karyawan", null, null, null, null, null, null, true));
        for (EmployeeResponseVm allPosition : allEmployees) {
            defaultComboBoxModel.addElement(allPosition);
        }
        jcKaryawan.setModel(defaultComboBoxModel);
        jcKaryawan.setRenderer(new ComboBoxListCellRender());
    }

    private void loadComboBoxRoleValues() {
        DefaultComboBoxModel<Role> defaultComboBoxModel = new DefaultComboBoxModel<>();
        allRoles = roleController.findAllRoles();
        defaultComboBoxModel.addElement(new Role(null, "Pilih Role"));
        for (Role role : allRoles) {
            defaultComboBoxModel.addElement(role);
        }
        jcRole.setModel(defaultComboBoxModel);
        jcRole.setRenderer(new ComboBoxListCellRender());
    }

    public static void main(String args[]) {
     FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("addThemes");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tambahAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Karyawan;
    private javax.swing.JLabel Karyawan1;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Telepon;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username;
    private javax.swing.JButton btSimpan;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JLabel idKaryawan;
    private javax.swing.JRadioButton jAktif;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<EmployeeResponseVm> jcKaryawan;
    private javax.swing.JComboBox<Role> jcRole;
    private javax.swing.JRadioButton jtidakAktif;
    private javax.swing.ButtonGroup status;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel subTitle2;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txFirst;
    private javax.swing.JTextField txLast;
    private javax.swing.JTextField txNumber;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
