package com.megayasa.Frontend.Asset.Table;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.megayasa.Frontend.View.Personalia.editKaryawan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Ridho Multazam
 */
public class PanelDelete extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelDelete() {
        initComponents();
        btDelete.setIcon(new FlatSVGIcon("iconSVG/delete.svg", 0.35f));
    }

    public void initEvent(TableActionDelete event, int row) {
        btDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btDelete = new com.megayasa.Frontend.Asset.Table.ActionButton();

        setPreferredSize(new java.awt.Dimension(96, 36));

        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.megayasa.Frontend.Asset.Table.ActionButton btDelete;
    // End of variables declaration//GEN-END:variables
}
