/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.megayasa.Frontend.View.Auth;

import javax.swing.JFrame;

/**
 *
 * @author Rimuza
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    
    int xx, xy;
    
    
    
    public loginPage() {
        initComponents();
        txUsername.setBackground(new java.awt.Color(0,0,0,1));
        txPassword.setBackground(new java.awt.Color(0,0,0,1));
        
        txUsername.setText("USERNAME");
        txPassword.setText("PASSWORD");

//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
          // Menambahkan window listener untuk menangani event windowDeiconified
//        addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowDeiconified(WindowEvent e) {
//                // Set frame menjadi fullscreen ketika diaktifkan dari taskbar
//                setExtendedState(JFrame.MAXIMIZED_BOTH);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_close = new javax.swing.JLabel();
        bt_minimize = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        txPassword = new javax.swing.JPasswordField();
        Login = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        forgotPassword = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 72, 192));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_close.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close-30.png"))); // NOI18N
        bt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_closeMouseClicked(evt);
            }
        });
        jPanel1.add(bt_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        bt_minimize.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize-30.png"))); // NOI18N
        bt_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(bt_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 30, 30));

        Username.setBackground(new java.awt.Color(33, 72, 192));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Username.png"))); // NOI18N
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 300, 45));

        txUsername.setBackground(new java.awt.Color(33, 72, 192));
        txUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txUsername.setForeground(new java.awt.Color(255, 255, 255));
        txUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txUsername.setText("USERNAME");
        txUsername.setBorder(null);
        jPanel1.add(txUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 300, 45));
        txUsername.getAccessibleContext().setAccessibleName("");

        Password.setBackground(new java.awt.Color(33, 72, 192));
        Password.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Password.png"))); // NOI18N
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 395, 300, 45));

        txPassword.setBackground(new java.awt.Color(33, 72, 192));
        txPassword.setForeground(new java.awt.Color(255, 255, 255));
        txPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPassword.setText("PASSWORD");
        txPassword.setBorder(null);
        jPanel1.add(txPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 395, 300, 45));

        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Login-btn.png"))); // NOI18N
        Login.setMaximumSize(new java.awt.Dimension(300, 45));
        Login.setMinimumSize(new java.awt.Dimension(300, 45));
        Login.setPreferredSize(new java.awt.Dimension(300, 45));
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 483, 300, 45));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/worker-male-skin-type-3-100.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 170, 124, 117));

        forgotPassword.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassword.setText("Forgot password?");
        jPanel1.add(forgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 539, 146, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("copyright © PT MEGAYASA ENGINEERING All rights reserved");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 680, -1, -1));

        Bg.setBackground(new java.awt.Color(33, 72, 192));
        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg-login.png"))); // NOI18N
        Bg.setMaximumSize(new java.awt.Dimension(1280, 720));
        Bg.setMinimumSize(new java.awt.Dimension(1280, 720));
        Bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_minimizeMouseClicked
            this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_bt_minimizeMouseClicked

    private void bt_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeMouseClicked
        dispose();
    }//GEN-LAST:event_bt_closeMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        String pass=txPassword.getText();
        if(pass.equals("PASSWORD")){
            txPassword.setText("");
        }
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        String pass=txPassword.getText();
        if(pass.equals("") ||pass.equals("PASSWORD")){
            txPassword.setText("PASSWORD");
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        String username=txUsername.getText();
        if(username.equals("USERNAME")){
            txUsername.setText("");
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        String username=txUsername.getText();
        if(username.equals("") ||username.equals("USERNAME")){
            txUsername.setText("USERNAME");
        }
    }//GEN-LAST:event_UsernameFocusLost
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel bt_close;
    private javax.swing.JLabel bt_minimize;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
