package com.megayasa.Frontend.View.Personalia;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.megayasa.Backend.Models.Position;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Font;
import javax.swing.*;

/**
 *
 * @author Ridho Multazam
 */
public class laporAbsensi extends javax.swing.JFrame {


    /**
     * Creates new form Test
     */
    public laporAbsensi() {
        initComponents();
        btCalendar.setIcon(new FlatSVGIcon("iconSVG/btCalendar.svg", 0.35f));
        
        new JProgressBar().setIndeterminate(true);
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
//                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        Karyawan = new javax.swing.JLabel();
        karyawan = new javax.swing.JComboBox();
        Tanggal = new javax.swing.JLabel();
        txDate = new javax.swing.JTextField();
        btCalendar = new javax.swing.JButton();
        keterangan = new javax.swing.JLabel();
        Keterangan = new javax.swing.JComboBox();
        Alamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCatatan = new javax.swing.JTextArea();
        btSimpan = new javax.swing.JButton();

        dateChooser.setForeground(new java.awt.Color(15, 42, 61));
        dateChooser.setTextRefernce(txDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 67, 69));
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "font:bold +1",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "wrap,al lead",
                "",
                "",
                "",
                "split 2",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Absensi Karyawan");
        crazyPanel1.add(Title);

        subTitle.setText("Laporan Kehadiran");
        crazyPanel1.add(subTitle);

        Karyawan.setText("Nama Karyawan");
        crazyPanel1.add(Karyawan);

        karyawan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Karyawan" }));
        crazyPanel1.add(karyawan);

        Tanggal.setText("Tanggal");
        crazyPanel1.add(Tanggal);

        txDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        crazyPanel1.add(txDate);

        btCalendar.setMaximumSize(new java.awt.Dimension(72, 23));
        btCalendar.setMinimumSize(new java.awt.Dimension(72, 23));
        btCalendar.setPreferredSize(new java.awt.Dimension(72, 23));
        btCalendar.setSelected(true);
        btCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalendarActionPerformed(evt);
            }
        });
        crazyPanel1.add(btCalendar);

        keterangan.setText("Keterangan");
        crazyPanel1.add(keterangan);

        Keterangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Izin", "Cuti", "Sakit", "Alpa" }));
        crazyPanel1.add(Keterangan);

        Alamat.setText("Catatan");
        crazyPanel1.add(Alamat);

        jtCatatan.setColumns(20);
        jtCatatan.setRows(3);
        jScrollPane1.setViewportView(jtCatatan);

        crazyPanel1.add(jScrollPane1);

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSimpan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalendarActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_btCalendarActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpanActionPerformed


    public static void main(String args[]) {
     FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("addThemes");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new laporAbsensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Karyawan;
    private javax.swing.JComboBox Keterangan;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btCalendar;
    private javax.swing.JButton btSimpan;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtCatatan;
    private javax.swing.JComboBox karyawan;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel subTitle;
    private javax.swing.JTextField txDate;
    // End of variables declaration//GEN-END:variables
}
