package com.megayasa.Frontend.View.Personalia;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Font;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Ridho Multazam
 */
public class tambahKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public tambahKaryawan() {
        initComponents();
        new JProgressBar().setIndeterminate(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txFirst = new javax.swing.JTextField();
        txLast = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txBirthday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jk = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txIdentity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 67, 69));

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "font:bold +1",
                "",
                "showClearButton:true;JTextField.placeholderText=Nama Depan",
                "showClearButton:true;JTextField.placeholderText=Nama Belakang",
                "",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true;JTextField.placeholderText=KTP",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "wrap,al lead",
                "",
                "split 2",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail"
            }
        ));

        jLabel1.setText("Tambah Karyawan");
        crazyPanel1.add(jLabel1);

        jLabel2.setText("Data Pribadi");
        crazyPanel1.add(jLabel2);

        jLabel4.setText("Nama Lengkap");
        crazyPanel1.add(jLabel4);
        crazyPanel1.add(txFirst);
        crazyPanel1.add(txLast);

        jLabel5.setText("Tanggal Lahir");
        crazyPanel1.add(jLabel5);
        crazyPanel1.add(txBirthday);

        jLabel6.setText("Alamat");
        crazyPanel1.add(jLabel6);
        crazyPanel1.add(txAddress);

        jLabel12.setText("Jenis Kelamin");
        crazyPanel1.add(jLabel12);

        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        crazyPanel1.add(jk);

        jLabel13.setText("No Telepon");
        crazyPanel1.add(jLabel13);
        crazyPanel1.add(txNumber);

        jLabel14.setText("No Identitas");
        crazyPanel1.add(jLabel14);
        crazyPanel1.add(txIdentity);

        jButton1.setText("Simpan");
        crazyPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
     FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("addThemes");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tambahKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JTextField txAddress;
    private javax.swing.JTextField txBirthday;
    private javax.swing.JTextField txFirst;
    private javax.swing.JTextField txIdentity;
    private javax.swing.JTextField txLast;
    private javax.swing.JTextField txNumber;
    // End of variables declaration//GEN-END:variables
}
